Parameters:
  BucketName:
    Type: String
    Default: photo-sync-trashcanmonster8
Resources:
  PhotoBuckets:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt ReductionLambda.Arn
      Tags:
        - Key: Project
          Value: photo-sync
  InvokeReductionLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ReductionLambda
      Principal: s3.amazonaws.com
      SourceArn: !Sub 'arn:aws:s3:::${BucketName}'
      SourceAccount: !Ref AWS::AccountId
  ReductionLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: 
              Service: 
                - lambda.amazonaws.com
            Action: 
              - sts:AssumeRole
      Description: Role for reducer lambda
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
      Policies:
        - PolicyName: createObjects
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - s3:PutObject
              Resource:  !Sub 'arn:aws:s3:::${BucketName}-reduced/*'
      RoleName: ReducerLambdaRole
      Tags:
        - Key: Project
          Value: photo-sync
  ReductionLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref BucketName
        S3Key: function.zip
        ZipFile: |
          export.handler = () => {
            print("hello")
          }
      Description: Reduces image size for future viewing
      FunctionName: reduceImage
      Role: !GetAtt ReductionLambdaRole.Arn
      Runtime: nodejs12.x
      Handler: index.handler